FROM mcr.microsoft.com/dotnet/sdk:6.0 as BuildStage
WORKDIR /app
COPY *.csproj ./
RUN dotnet restore
COPY . ./
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /deploy
COPY --from=BuildStage /app/out . 
ENTRYPOINT ["dotnet","PaymentService.dll"]